// <auto-generated />
using System;
using AssetManagement.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagement.Data.Migrations
{
    [DbContext(typeof(AssetManagementDbContext))]
    [Migration("20221209044205_AddReturnRequest")]
    partial class AddReturnRequest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AssetManagement.Domain.Models.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc"),
                            ConcurrencyStamp = "2e5b24f5-62ed-47d7-881a-78eb23843cdd",
                            Description = "Administrator role",
                            Name = "Admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = new Guid("12147fe0-4571-4ad2-b8f7-d2c863eb78a5"),
                            ConcurrencyStamp = "4a97a439-2f79-4342-8a7f-b71d713f1a43",
                            Description = "Staff role",
                            Name = "Staff",
                            NormalizedName = "staff"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLoginFirstTime")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1cb5e9ab-199d-4a33-a593-c695621acb8f",
                            CreatedDate = new DateTime(2022, 12, 9, 11, 42, 4, 733, DateTimeKind.Local).AddTicks(2260),
                            Dob = new DateTime(2000, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "adminhcm@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Toan",
                            Gender = 0,
                            IsDeleted = false,
                            IsLoginFirstTime = false,
                            LastName = "Bach",
                            Location = 0,
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedEmail = "adminhcm@gmail.com",
                            NormalizedUserName = "adminhcm",
                            PasswordHash = "AQAAAAEAACcQAAAAEBkzrANreNLBJMzEnCEHbG9AS4v8Xg15kHzSXQvJrIm82C19eA5IpRhtE30RvADFSQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            StaffCode = "SD0001",
                            TwoFactorEnabled = false,
                            UserName = "adminhcm"
                        },
                        new
                        {
                            Id = new Guid("69bd714f-9576-45ba-b5b7-f00649be00bf"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c2508d97-f190-4469-9c18-551376338181",
                            CreatedDate = new DateTime(2022, 12, 9, 11, 42, 4, 739, DateTimeKind.Local).AddTicks(6670),
                            Dob = new DateTime(2000, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "adminhn@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Toan",
                            Gender = 0,
                            IsDeleted = false,
                            IsLoginFirstTime = true,
                            LastName = "Bach",
                            Location = 1,
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedEmail = "adminhn@gmail.com",
                            NormalizedUserName = "adminhn",
                            PasswordHash = "AQAAAAEAACcQAAAAEBZiGcrOw9olMHc/R4dbZQ5PikYOU/tOWQFQkyZyVdQ8WaIMjBfF+TYImxA3BUOyiA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            StaffCode = "SD0002",
                            TwoFactorEnabled = false,
                            UserName = "adminhn"
                        },
                        new
                        {
                            Id = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "751a93aa-5c0e-4b3f-85f2-83df318a5870",
                            CreatedDate = new DateTime(2022, 12, 9, 11, 42, 4, 745, DateTimeKind.Local).AddTicks(5708),
                            Dob = new DateTime(2000, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Toan",
                            Gender = 1,
                            IsDeleted = false,
                            IsLoginFirstTime = true,
                            LastName = "Bach",
                            Location = 1,
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedEmail = "staff@gmail.com",
                            NormalizedUserName = "staff1",
                            PasswordHash = "AQAAAAEAACcQAAAAEFBCeRZX4WoBso0NdFYz31da6UaYz4FffbxDpMPkAUWbPdtbhCi2ZElWkAYVk2poVw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            StaffCode = "SD0003",
                            TwoFactorEnabled = false,
                            UserName = "staff1"
                        },
                        new
                        {
                            Id = new Guid("70bd814f-9576-45ba-b5b7-f00649be00de"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2741f28f-55c8-4a49-8a23-5df37988d8f8",
                            CreatedDate = new DateTime(2022, 12, 9, 11, 42, 4, 751, DateTimeKind.Local).AddTicks(9559),
                            Dob = new DateTime(2000, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Toan",
                            Gender = 1,
                            IsDeleted = false,
                            IsLoginFirstTime = true,
                            LastName = "Bach",
                            Location = 1,
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedEmail = "staff@gmail.com",
                            NormalizedUserName = "staff2",
                            PasswordHash = "AQAAAAEAACcQAAAAEFrAB4gkh35v5L3zAzlUxlvhwa9tebK1AQLG0+EM3JVtSF2+hPYCuxqbwGiV/VYDdQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            StaffCode = "SD0004",
                            TwoFactorEnabled = false,
                            UserName = "staff2"
                        },
                        new
                        {
                            Id = new Guid("73bd714f-9576-45ba-b5b7-f00649be00de"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1788c929-2042-4516-bce0-9e843500f97a",
                            CreatedDate = new DateTime(2022, 12, 9, 11, 42, 4, 758, DateTimeKind.Local).AddTicks(3522),
                            Dob = new DateTime(2000, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staffdis@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Toan",
                            Gender = 1,
                            IsDeleted = true,
                            IsLoginFirstTime = true,
                            LastName = "Bach",
                            Location = 1,
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedEmail = "staffdis@gmail.com",
                            NormalizedUserName = "staffdis",
                            PasswordHash = "AQAAAAEAACcQAAAAEAefH9KFnKOPiWi53WS2qJRFK/ShGwOgFxf8wThggUzkdXCxmcMv7l4H5dRqqTUzkg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            StaffCode = "SD0005",
                            TwoFactorEnabled = false,
                            UserName = "staffDis"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InstalledDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetCode = "LA100001",
                            CategoryId = 2,
                            InstalledDate = new DateTime(2022, 12, 9, 11, 42, 4, 758, DateTimeKind.Local).AddTicks(3770),
                            IsDeleted = false,
                            Location = 0,
                            Name = "Laptop 1",
                            Specification = "Core i1, 1GB RAM, 150 GB HDD, Window 1",
                            State = 1
                        },
                        new
                        {
                            Id = 2,
                            AssetCode = "LA100002",
                            CategoryId = 1,
                            InstalledDate = new DateTime(2022, 12, 9, 11, 42, 4, 758, DateTimeKind.Local).AddTicks(3787),
                            IsDeleted = true,
                            Location = 0,
                            Name = "Laptop 2",
                            Specification = "Core i2, 2GB RAM, 250 GB HDD, Window 2",
                            State = 0
                        },
                        new
                        {
                            Id = 3,
                            AssetCode = "LA100003",
                            CategoryId = 2,
                            InstalledDate = new DateTime(2022, 12, 9, 11, 42, 4, 758, DateTimeKind.Local).AddTicks(3797),
                            IsDeleted = false,
                            Location = 0,
                            Name = "Laptop 3",
                            Specification = "Core i3, 3GB RAM, 350 GB HDD, Window 3",
                            State = 1
                        },
                        new
                        {
                            Id = 4,
                            AssetCode = "LA100004",
                            CategoryId = 1,
                            InstalledDate = new DateTime(2022, 12, 9, 11, 42, 4, 758, DateTimeKind.Local).AddTicks(3806),
                            IsDeleted = true,
                            Location = 0,
                            Name = "Laptop 4",
                            Specification = "Core i4, 4GB RAM, 450 GB HDD, Window 4",
                            State = 0
                        },
                        new
                        {
                            Id = 5,
                            AssetCode = "LA100005",
                            CategoryId = 2,
                            InstalledDate = new DateTime(2022, 12, 9, 11, 42, 4, 758, DateTimeKind.Local).AddTicks(3815),
                            IsDeleted = false,
                            Location = 0,
                            Name = "Laptop 5",
                            Specification = "Core i5, 5GB RAM, 550 GB HDD, Window 5",
                            State = 1
                        },
                        new
                        {
                            Id = 6,
                            AssetCode = "LA100006",
                            CategoryId = 1,
                            InstalledDate = new DateTime(2022, 12, 9, 11, 42, 4, 758, DateTimeKind.Local).AddTicks(3825),
                            IsDeleted = true,
                            Location = 0,
                            Name = "Laptop 6",
                            Specification = "Core i6, 6GB RAM, 650 GB HDD, Window 6",
                            State = 0
                        },
                        new
                        {
                            Id = 7,
                            AssetCode = "LA100007",
                            CategoryId = 2,
                            InstalledDate = new DateTime(2022, 12, 9, 11, 42, 4, 758, DateTimeKind.Local).AddTicks(3834),
                            IsDeleted = false,
                            Location = 0,
                            Name = "Laptop 7",
                            Specification = "Core i7, 7GB RAM, 750 GB HDD, Window 7",
                            State = 1
                        },
                        new
                        {
                            Id = 8,
                            AssetCode = "LA100008",
                            CategoryId = 1,
                            InstalledDate = new DateTime(2022, 12, 9, 11, 42, 4, 758, DateTimeKind.Local).AddTicks(3843),
                            IsDeleted = true,
                            Location = 0,
                            Name = "Laptop 8",
                            Specification = "Core i8, 8GB RAM, 850 GB HDD, Window 8",
                            State = 0
                        },
                        new
                        {
                            Id = 9,
                            AssetCode = "LA100009",
                            CategoryId = 2,
                            InstalledDate = new DateTime(2022, 12, 9, 11, 42, 4, 758, DateTimeKind.Local).AddTicks(3852),
                            IsDeleted = false,
                            Location = 0,
                            Name = "Laptop 9",
                            Specification = "Core i9, 9GB RAM, 950 GB HDD, Window 9",
                            State = 1
                        },
                        new
                        {
                            Id = 10,
                            AssetCode = "LA1000010",
                            CategoryId = 1,
                            InstalledDate = new DateTime(2022, 12, 9, 11, 42, 4, 758, DateTimeKind.Local).AddTicks(3943),
                            IsDeleted = true,
                            Location = 0,
                            Name = "Laptop 10",
                            Specification = "Core i10, 10GB RAM, 1050 GB HDD, Window 10",
                            State = 0
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("AssignedTo");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetId = 1,
                            AssignedBy = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignedTo = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            IsDeleted = false,
                            Note = "Note for assignment 1",
                            ReturnedDate = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 1
                        },
                        new
                        {
                            Id = 2,
                            AssetId = 2,
                            AssignedBy = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignedTo = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            IsDeleted = false,
                            Note = "Note for assignment 2",
                            ReturnedDate = new DateTime(2022, 12, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 0
                        },
                        new
                        {
                            Id = 3,
                            AssetId = 3,
                            AssignedBy = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignedTo = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            IsDeleted = false,
                            Note = "Note for assignment 3",
                            ReturnedDate = new DateTime(2022, 12, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 1
                        },
                        new
                        {
                            Id = 4,
                            AssetId = 4,
                            AssignedBy = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignedTo = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            IsDeleted = false,
                            Note = "Note for assignment 4",
                            ReturnedDate = new DateTime(2022, 12, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 0
                        },
                        new
                        {
                            Id = 5,
                            AssetId = 5,
                            AssignedBy = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignedTo = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            IsDeleted = false,
                            Note = "Note for assignment 5",
                            ReturnedDate = new DateTime(2022, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 1
                        },
                        new
                        {
                            Id = 6,
                            AssetId = 6,
                            AssignedBy = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignedTo = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            IsDeleted = false,
                            Note = "Note for assignment 6",
                            ReturnedDate = new DateTime(2022, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 0
                        },
                        new
                        {
                            Id = 7,
                            AssetId = 7,
                            AssignedBy = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignedTo = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            IsDeleted = false,
                            Note = "Note for assignment 7",
                            ReturnedDate = new DateTime(2022, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 1
                        },
                        new
                        {
                            Id = 8,
                            AssetId = 8,
                            AssignedBy = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignedTo = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            IsDeleted = false,
                            Note = "Note for assignment 8",
                            ReturnedDate = new DateTime(2022, 12, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 0
                        },
                        new
                        {
                            Id = 9,
                            AssetId = 9,
                            AssignedBy = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignedTo = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            IsDeleted = false,
                            Note = "Note for assignment 9",
                            ReturnedDate = new DateTime(2022, 12, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 1
                        },
                        new
                        {
                            Id = 10,
                            AssetId = 10,
                            AssignedBy = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignedTo = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            IsDeleted = false,
                            Note = "Note for assignment 10",
                            ReturnedDate = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 0
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Laptop",
                            Prefix = "LA"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Monitor",
                            Prefix = "MO"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Personal Computer",
                            Prefix = "PC"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Models.ReturnRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("AcceptedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedBy");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("AssignmentId");

                    b.ToTable("ReturnRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedBy = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignmentId = 1,
                            ReturnedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 0
                        },
                        new
                        {
                            Id = 2,
                            AssignedBy = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignmentId = 2,
                            ReturnedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 0
                        },
                        new
                        {
                            Id = 3,
                            AssignedBy = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignmentId = 3,
                            ReturnedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 0
                        },
                        new
                        {
                            Id = 4,
                            AssignedBy = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignmentId = 4,
                            ReturnedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 0
                        },
                        new
                        {
                            Id = 5,
                            AssignedBy = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignmentId = 5,
                            ReturnedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 0
                        },
                        new
                        {
                            Id = 6,
                            AssignedBy = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignmentId = 6,
                            ReturnedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 0
                        },
                        new
                        {
                            Id = 7,
                            AssignedBy = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignmentId = 7,
                            ReturnedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 0
                        },
                        new
                        {
                            Id = 8,
                            AssignedBy = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignmentId = 8,
                            ReturnedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 0
                        },
                        new
                        {
                            Id = 9,
                            AssignedBy = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignmentId = 9,
                            ReturnedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 0
                        },
                        new
                        {
                            Id = 10,
                            AssignedBy = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            AssignedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            AssignmentId = 10,
                            ReturnedDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            State = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            RoleId = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc")
                        },
                        new
                        {
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00bf"),
                            RoleId = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc")
                        },
                        new
                        {
                            UserId = new Guid("73bd714f-9576-45ba-b5b7-f00649be00de"),
                            RoleId = new Guid("12147fe0-4571-4ad2-b8f7-d2c863eb78a5")
                        },
                        new
                        {
                            UserId = new Guid("70bd714f-9576-45ba-b5b7-f00649be00de"),
                            RoleId = new Guid("12147fe0-4571-4ad2-b8f7-d2c863eb78a5")
                        },
                        new
                        {
                            UserId = new Guid("70bd814f-9576-45ba-b5b7-f00649be00de"),
                            RoleId = new Guid("12147fe0-4571-4ad2-b8f7-d2c863eb78a5")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AssetManagement.Domain.Models.Asset", b =>
                {
                    b.HasOne("AssetManagement.Domain.Models.Category", "Category")
                        .WithMany("Assets")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AssetManagement.Domain.Models.Assignment", b =>
                {
                    b.HasOne("AssetManagement.Domain.Models.Asset", "Asset")
                        .WithMany("Assignments")
                        .HasForeignKey("AssetId");

                    b.HasOne("AssetManagement.Domain.Models.AppUser", "AssignedByAppUser")
                        .WithMany("AssignedByAssignments")
                        .HasForeignKey("AssignedBy");

                    b.HasOne("AssetManagement.Domain.Models.AppUser", "AssignedToAppUser")
                        .WithMany("AssignedToAssignments")
                        .HasForeignKey("AssignedTo");

                    b.Navigation("Asset");

                    b.Navigation("AssignedByAppUser");

                    b.Navigation("AssignedToAppUser");
                });

            modelBuilder.Entity("AssetManagement.Domain.Models.ReturnRequest", b =>
                {
                    b.HasOne("AssetManagement.Domain.Models.AppUser", "AcceptedByUser")
                        .WithMany()
                        .HasForeignKey("AcceptedBy");

                    b.HasOne("AssetManagement.Domain.Models.AppUser", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetManagement.Domain.Models.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcceptedByUser");

                    b.Navigation("AssignedByUser");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("AssetManagement.Domain.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AssetManagement.Domain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AssetManagement.Domain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("AssetManagement.Domain.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetManagement.Domain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AssetManagement.Domain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssetManagement.Domain.Models.AppUser", b =>
                {
                    b.Navigation("AssignedByAssignments");

                    b.Navigation("AssignedToAssignments");
                });

            modelBuilder.Entity("AssetManagement.Domain.Models.Asset", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("AssetManagement.Domain.Models.Category", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
